# -*- coding: utf-8 -*-
"""MovieRatingPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPMcpMeqR9g1tczFDF_pt0VJf1aqhM3i

# **🎬 MOVIE RATING PREDICTION**

**DATA HANDLING**

STEP 1: IMPORT LIBRARIES
"""

#data handling
import pandas as pd
import numpy as np

#visualization
import matplotlib.pyplot as plt
import seaborn as sns

#machine learning
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

"""STEP 2 : LOAD DATASET"""

df=pd.read_csv("IMDb Movies India.csv" , encoding="latin-1")
df.head()

"""**DATA EXPLORATION**

STEP 3 : UNDERSTAND DATA
"""

df.info()
df.isnull().sum()

"""**DATA CLEANING**

STEP 4 : REMOVE ROWS WHERE RATING IS MISSING
"""

df=df.dropna(subset=["Rating"])

"""STEP 5 : CLEAN YEAR COLUMN"""

df["Year"] = df["Year"].astype(str)
df["Year"]=df["Year"].str.replace("(" ,"", regex= False)
df["Year"]=df["Year"].str.replace(")","", regex= False)
df["Year"]=pd.to_numeric(df["Year"] , errors="coerce")

"""STEP 6 : CLEAN DURATION

"""

df["Duration"]=df["Duration"].str.replace("min","",regex=False)
df["Duration"]=pd.to_numeric(df["Duration"], errors="coerce")

"""STEP 7 : CLEAN VOTES"""

df["Votes"] = df["Votes"].astype(str)
df["Votes"]=df["Votes"].str.replace(",","",regex=False)
df["Votes"]=pd.to_numeric(df["Votes"], errors="coerce")

"""STEP 8 : DROP MOVIE NAME (not useful)"""

df.drop("Name",axis=1,inplace=True)

"""STEP 9 : FILL REMAINING MISSSING VALUES"""

df=df.fillna(0)

"""STEP 10 : CONVERT TEXT TO NUMBERS"""

df=pd.get_dummies(df)

"""STEP 11 : DEFINE X AND Y"""

X=df.drop("Rating",axis=1)
y=df["Rating"]

"""STEP 12 : TRAIN TEST SPLIT"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,test_size=0.2, random_state=42
)

"""STEP 13 : TRAIN MODEL"""

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

"""STEP 14 : PREDICT"""

pred=model.predict(X_test)

"""STEP 15 : CHECK ERROR"""

print("MAE:",mean_absolute_error(y_test,pred))

"""**CONCLUSION:**

 This project built a machine learning model to predict movie ratings using features like genre, director, votes, duration, and year. After cleaning and preprocessing the dataset, a Random Forest Regressor was trained and evaluated using Mean Absolute Error (MAE). The model was able to estimate ratings reasonably well, showing how different movie attributes influence audience ratings. This project helped in understanding the complete data science workflow, including data cleaning, feature engineering, model training, and evaluation.

"""